// 网络暴力内容检测
export const DETECT_VIOLENCE_REQUEST = 'DETECT_VIOLENCE_REQUEST';
export const DETECT_VIOLENCE_SUCCESS = 'DETECT_VIOLENCE_SUCCESS';
export const DETECT_VIOLENCE_FAIL = 'DETECT_VIOLENCE_FAIL';

// 获取反网络暴力资源
export const GET_RESOURCES_REQUEST = 'GET_RESOURCES_REQUEST';
export const GET_RESOURCES_SUCCESS = 'GET_RESOURCES_SUCCESS';
export const GET_RESOURCES_FAIL = 'GET_RESOURCES_FAIL';

// 举报网络暴力
export const REPORT_VIOLENCE_REQUEST = 'REPORT_VIOLENCE_REQUEST';
export const REPORT_VIOLENCE_SUCCESS = 'REPORT_VIOLENCE_SUCCESS';
export const REPORT_VIOLENCE_FAIL = 'REPORT_VIOLENCE_FAIL';

// 获取反网络暴力案例
export const GET_CASE_REQUEST = 'GET_CASE_REQUEST';
export const GET_CASE_SUCCESS = 'GET_CASE_SUCCESS';
export const GET_CASE_FAIL = 'GET_CASE_FAIL';

// 点赞案例
export const LIKE_CASE_REQUEST = 'LIKE_CASE_REQUEST';
export const LIKE_CASE_SUCCESS = 'LIKE_CASE_SUCCESS';
export const LIKE_CASE_FAIL = 'LIKE_CASE_FAIL';

// 分享案例
export const SHARE_CASE_REQUEST = 'SHARE_CASE_REQUEST';
export const SHARE_CASE_SUCCESS = 'SHARE_CASE_SUCCESS';
export const SHARE_CASE_FAIL = 'SHARE_CASE_FAIL';

// 添加鼓励留言
export const ADD_ENCOURAGEMENT_REQUEST = 'ADD_ENCOURAGEMENT_REQUEST';
export const ADD_ENCOURAGEMENT_SUCCESS = 'ADD_ENCOURAGEMENT_SUCCESS';
export const ADD_ENCOURAGEMENT_FAIL = 'ADD_ENCOURAGEMENT_FAIL';

// 获取鼓励留言
export const GET_ENCOURAGEMENTS_REQUEST = 'GET_ENCOURAGEMENTS_REQUEST';
export const GET_ENCOURAGEMENTS_SUCCESS = 'GET_ENCOURAGEMENTS_SUCCESS';
export const GET_ENCOURAGEMENTS_FAIL = 'GET_ENCOURAGEMENTS_FAIL';